version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: chore
    groups:
      # Specify a name for the group, which will be used in pull request titles
      # and branch names
      dependencies:
        # Define patterns to include dependencies in the group (based on
        # dependency name)
        patterns:
          - "*"
    # ignore:
    # - dependency-name: "..."
