name: 'Pull Request Checks'
on:
  pull_request:
    branches:
    - main
    
jobs:
  cancel-runs:
    name: 'Fast Checks'
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: 'Cancel Previous Runs'
      uses: styfle/cancel-workflow-action@0.12.0
      with:
        all_but_latest: true
        access_token: ${{ github.token }}
    - name: 'Validate Pull Request Title'
      uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        types: |
          fix
          feat
          docs
          ci
          chore
          chore(.+)
        requireScope: false
        subjectPattern: ^[A-Z].+$
        subjectPatternError: |
          The subject "{subject}" found in the pull request title "{title}"
          didn't match the configured pattern. Please ensure that the subject
          starts with an uppercase character.
        wip: true
        validateSingleCommit: false

    - name: 'Check Commit Message'
      uses: gsactions/commit-message-checker@v2
      with:
        pattern: "^(fix|feat|docs|ci|chore).+$"
        error: "Subject doesn't start with required words"
        excludeDescription: truer

  build-and-test:
    name: 'Build And Test'
    needs: [cancel-runs]
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    # - name: 'Setup Docker Compose'
    #   uses: KengoTODA/actions-setup-docker-compose@main
    #   with:
    #     version: 'v2.14.1'

    - name: 'Checkout'
      uses: actions/checkout@v4
      with :
        fetch-depth: 0
        # https://github.com/semantic-release/semantic-release/issues/1890#issuecomment-974512960
        ref: ${{ github.head_ref }}

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.x'
        
    # - name: 'Pre Commit Checks'
    #   uses: pre-commit/action@v3.0.0

    - name: 'Run tests'
      run: |
        dotnet test

    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.2.1
      with:
        reports: './CoverletReport/*.xml'
        targetdir: './coveragereport'
        reporttypes: 'HtmlInline;Cobertura'

    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: ./coveragereport/*.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md

    - name: 'Setup NodeJS'
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Get Version And Publish Nuget
      # https://github.com/semantic-release/semantic-release/issues/1890#issuecomment-974512960
      run: |
        unset GITHUB_ACTIONS
        export NEXT_VERSION=$(npx semantic-release --no-ci --dry-run --plugins "@semantic-release/commit-analyzer" | grep -oP 'The next release version is \K[0-9]+\.[0-9]+\.[0-9]+.*' | sed -E "/[0-9]+\.[0-9]+\.[0-9]+-.+/ s/$/.$(git rev-parse --short HEAD)/")
        echo $NEXT_VERSION | tee build-version.txt

    - name: Upload build-version.txt
      uses: actions/upload-artifact@v3
      with: 
        name: build-version.txt
        path: build-version.txt


